services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: med
      POSTGRES_PASSWORD: med
      POSTGRES_DB: med
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  pgdata:
